openapi: 3.0.0
info:
  version: 1.0.0
components:
  schemas:
    Volunteer:
      type: object
      properties:
        userDetails:
          type: object
    Event:
      type: object
      properties:
        eventDetails:
          type: object
  parameters:
    username:
      name: username
      in: query
      required: true
      schema:
        type: string
    password:
      name: password
      in: query
      required: true
      schema:
        type: string
paths:
  /add-volunteer:
    post:
      summary: Add a volunteer
      requestBody:
        description: Details of the volunteer
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Volunteer"
      responses:
        "200":
          description: success
        "500":
          description: failure
  /add-event:
    post:
      summary: Add an event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: success
        "500":
          description: failure
  /get-events:
    get:
      description: Gets all events
      responses:
        "200":
          description: success
        "500":
          description: failure
  /get-authentication-match:
    get:
      description: Validates a user's attempt to login
      parameters:
        - $ref: "#/components/parameters/username"
        - $ref: "#/components/parameters/password"
      responses:
        "200":
          description: success
        "500":
          description: failure
          
