openapi: 3.0.0
info:
  version: 1.0.0
  title: 8forchange
  license:
    name: MIT
servers:
  - url: 'https://localhost:3000'
paths:
  /volunteer:
    get:
      summary: Details about a volunteer
      operationId: listVolunteer
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the volunteer
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Details about a volunteer
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volunteer'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add a volunteer
      operationId: addVolunteer
      requestBody:
        description: Details of the volunteer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Volunteer'
      responses:
        '200':
          description: Addition of volunteer successful!
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /event:
    get:
      summary: Details about an event
      operationId: getEvent
      tags:
        - event
      parameters:
        - name: id
          in: query
          description: ID of the event
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Details about an event
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Volunteer:
      type: object
      required:
        - id
        - name
        - birthdate
        - sessionsCompleted
        - email
        - phone
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthdate:
          type: string
        sessionsCompleted:
          type: integer
          format: int64
        email:
          type: string
        phone:
          type: integer
          format: int64
    Event:
      type: object
      required:
        - id
        - name
        - startDate
        - endDate
        - startTime
        - endTime
        - address
        - area
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        address:
          type: string
        area:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
